baseURL: /
languageCode: en-us
title: Australian Imaging Service
caches:
  images:
    dir: :cacheDir/images

module:
  hugoVersion:
    extended: true
    min: "0.114.0"
  imports:
    - path: "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
      disable: false
    - path: "github.com/Australian-Imaging-Service/charts"
      disabled: false
      mounts:
        - source: docs/Deployment
          target: "content/docs/Technical Documentation/AIS Node/XNAT"
    - path: "github.com/Australian-Imaging-Service/pipelines"
      disabled: false
      mounts:
        - source: docs
          target: "content/docs/Technical Documentation/pipelines"

markup:
  tableOfContents:
    endLevel: 3
    startLevel: 1
  goldmark:
    renderer:
      unsafe: true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
  goldmark.parser:
    parser.attribute:
      block: true

theme:
  - tailbliss
  - lotusdocs

params:
  title_1: 'Unlocking Insights,'
  title_2: 'Shaping Discoveries'
  author: University of Sydney
  authorimage: ../assets/images/global/author.webp
  og_image: /images/tailbliss-cover.png
  moto: "A national federation for securely managing and analysing imaging data."
  description: ""
  disable_theme_toggle: false
  disable_stay_uptodate: false

  section1:
    heading: "Built for Australian research community"
    content: ''
    built_for:
      - title: 'Researchers'
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed erat nibh tristique ipsum.'
        border_class: 'border-left-blue'
      - title: 'Facility Staff'
        summary: 'Highly skilled scientists who contribute technically and intellectually to research projects.'
        border_class: 'border-left-green'
      - title: 'Hospital & Ethics Committee'
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed erat nibh tristique ipsum.'
        border_class: 'border-left-purple'
  section2:
    heading: "Easy, secure and powerful"
    content:
      - text: "We aim to increase research reproducibility and drive the adoption of innovative but trusted analysis techniques."
    analysis_techniques:
      - title: 'Secure Data Management'
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed erat nibh tristique ipsum.'
        classes: 'col-span-2 bg-gradient-right'
      - title: 'Automated Pipelines'
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed erat nibh tristique ipsum.'
        classes: 'col-span-3 bg-img'
        bg_image: 'images/main/automated_pipelines.jpg'
      - title: 'Interactive Analysis'
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed erat nibh tristique ipsum.'
        classes: 'col-span-3 bg-img'
        bg_image: 'images/main/interactive_analysis.jpg'
      - title: 'Machine Learning Tools'
        summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed erat nibh tristique ipsum.'
        classes: 'col-span-2 bg-gradient-left'

  section3:
    heading: "Our selected work"
    content:
      - text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    works:
      - title: 'Transforming Clinical Image Management and Analysis'
        summary: 'The Australian Imaging Service is enhancing imaging research on a global scale and making it more secure and easier.'
        featured_image: 'images/main/work1.png'
      - title: 'Building research capacity towards early detection of melanoma'
        summary: '45,000 avatars to develop next-generation skin cancer diagnosis.'
        featured_image: 'images/main/work2.png'
      - title: 'Interstitial Lung Disease Registry'
        summary: 'The ILD Registry provides a platform for consistency and continuity in data collection for patients with ILD.'
        featured_image: 'images/main/work3.png'

  section4:
    heading: "We drive national collaboration"
    content:
      - text: 'We partnered with top Imaging Research institutions Across Australia.'
    partners:
      - title: 'University of Sydney'
        featured_image: 'images/main/partner_logos/usyd.svg'
      - title: 'National Imaging Facility'
        featured_image: 'images/main/partner_logos/nif.svg'
      - title: 'Australian Access Federation'
        featured_image: 'images/main/partner_logos/aaf.svg'
      - title: 'QCIF'
        featured_image: 'images/main/partner_logos/qcif.svg'
      - title: 'UNSW'
        featured_image: 'images/main/partner_logos/unsw.svg'
      - title: 'The University of Queensland'
        featured_image: 'images/main/partner_logos/uq.svg'
      - title: 'Monash University'
        featured_image: 'images/main/partner_logos/monash.svg'
      - title: 'Macquarie University'
        featured_image: 'images/main/partner_logos/mqu.svg'
      - title: 'The University of Western Australia'
        featured_image: 'images/main/partner_logos/uwa.svg'
      - title: 'QUT'
        featured_image: 'images/main/partner_logos/qut.svg'

  section5:
    title: "Fasten your Imaging research with us."
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    button: 'Start today'
  social_media:
    github:
      enabled: true
      url: 'https://github.com/Australian-Imaging-Service/web-dev'
    facebook:
      enabled: true
      url: 'https://facebook.com/'
    instagram:
      enabled: true
      url: 'https://instagram.com/'
    twitter:
      enabled: true
      url: 'https://twitter.com/'

  about:
    section1:
      image: 'images/main/pages/federation.png'
      title: 'Federated model'
      description:
        - title: 'Edge Devices'
          description: 'Upload & process data from clinical sites and imaging facilities.'
        - title: 'Nodes'
          description: 'Linked data repositories with a shared library of containerized pipelines and analysis tools deployed on Kubernetes.'
        - title: 'Data Portal'
          description: 'Open frontend for findable metadata (opt-in).'
    funded_by:
      - title: 'Australian Research Data Commons'
        featured_image: 'images/main/partner_logos/ARDC.svg'
      - title: 'National Imaging Facility'
        featured_image: 'images/main/partner_logos/nif_rgb.svg'
      - title: 'Funded by the European Union'
        featured_image: 'images/main/partner_logos/FundedbytheEU.svg'
      - title: 'Medical Research Future Fund'
        featured_image: 'images/main/partner_logos/mrff.svg'

  google_fonts: [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]

  sans_serif_font: "Inter"     # Default is System font
  secondary_font: "Inter"     # Default is System font
  mono_font: "Fira Code" # Default is System font

  footer:
    copyright: "Â© :YEAR: Lotus Labs. Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"
    # version: true # includes git commit info

  social:
    github: ""        # YOUR_GITHUB_ID or YOUR_GITHUB_URL
    twitter: ""       # YOUR_TWITTER_ID
    # instagram: "colinwilson"     # YOUR_INSTAGRAM_ID
    # rss: true                    # show rss icon with link

  docs: # Parameters for the /docs 'template'
    title          : "Lotus Docs Example Site"           # default html title for documentation pages/sections
    darkMode       : true                                # enable dark mode option? default false

    prism          : true                                # enable syntax highlighting via Prism

    prismTheme     : "solarized-light"                           # (optional) - Set theme for PrismJS. Options include: lotusdocs (default), solarized-light, twilight, lucario

    # gitinfo
    repoURL        : "https://github.com/colinwilson/lotusdocs.dev"  # Git repository URL for your site [support for GitHub, GitLab, and BitBucket]
    repoBranch     : "release"
    editPage       : true                                # enable 'Edit this page' feature - default false
    lastMod        : true                                # enable 'Last modified' date on pages - default false
    lastModRelative: true                                # format 'Last modified' time as relative - default true

    sidebarIcons   : true                                # enable sidebar icons? default false
    breadcrumbs    : true                                # default is true
    backToTop      : true                                # enable back-to-top button? default true

    # ToC
    toc            : true                                # enable table of contents? default is true
    tocMobile      : true                                # enable table of contents in mobile view? default is true
    scrollSpy      : true                                # enable scrollspy on ToC? default is true

    # front matter
    descriptions   : true                                # enable front matter descriptions under content title?
    titleIcon      : true                                # enable front matter icon title prefix? default is false

    # content navigation
    navDesc        : true                                # include front matter descriptions in Prev/Next navigation cards
    navDescTrunc   : 30                                  # Number of characters by which to truncate the Prev/Next descriptions

    listDescTrunc  : 100                                 # Number of characters by which to truncate the list card description

    # Link behaviour
    intLinkTooltip : true                                # Enable a tooltip for internal links that displays info about the destination? default false
    # extLinkNewTab  : false                             # Open external links in a new Tab? default true
    # logoLinkURL: ""                                    # Set a custom URL destination for the top header logo link.

  flexsearch: # Parameters for FlexSearch
    enabled: trueS

menu:
  main:
    - identifier: features
      name: Features
      url: /features/
      weight: 20
    - identifier: docs
      name: Docs
      url: /docs/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 30
    - identifier: support
      name: Support
      url: /support/
      weight: 40
    # - identifier: news
    #   name: News
    #   url: /news/
    #   weight: 20
  categories:
    - identifier: prose
      name: Prose
      url: /prose/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20
  dropdown:
    - identifier: appearance
      pre: stars # can be stars, comments or piechart
      name: Appearance
      post: "Easy customization"
      url: "#"
      weight: 10
    - identifier: comments
      pre: comments # can be stars, comments or piechart
      name: Comments
      post: "Check your latest comments"
      url: "#"
      weight: 20
    - identifier: analytics
      pre: piechart # can be stars, comments or piechart
      name: Analytics
      post: "Take a look at your statistics"
      url: "#"
      weight: 30
  footer:
    - identifier: features
      name: Features
      url: '/features'
      weight: 10
    - name: 'Data Management'
      url: 'features/data_management'
      parent: features
    - name: 'Automated Pipelines'
      url: 'features/automated_pipelines'
      parent: features
    - name: 'Interactive Analysis'
      url: 'features/interactive_analysis'
      parent: features
    - name: 'Machine Learning'
      url: 'features/machine_learning'
      parent: features
    - identifier: docs
      name: Docs
      url: '/docs'
      weight: 20
    - name: 'Researchers'
      url: 'docs/researchers'
      parent: docs
    - name: 'Facilities'
      url: 'docs/facilities'
      parent: docs
    - name: 'Technical Documentation'
      url: 'docs/technical-documentation'
      parent: docs
    - identifier: about
      name: About
      url: '/about'
      weight: 30
    - name: 'Mission'
      url: 'about/mission'
      parent: about
    - name: 'Federation'
      url: 'about/federation'
      parent: about
    - name: 'Compliance'
      url: 'about/compliance'
      parent: about
    - name: 'Funders'
      url: 'about/funders'
      parent: about
    - identifier: support
      name: Support
      url: '/support'
      weight: 40
    - name: 'Find Nodes'
      url: 'support/find_nodes'
      parent: support
    - name: 'Contact Us'
      url: 'support/contact_us'
      parent: support

#markup:
#  goldmark:
#    renderer:
#      unsafe: true

taxonomies:
  category: Categories
  tag: Tags

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true
